# Permalinks
permalink:           pretty

# Setup
title:               'Mechatronics Intelligence Lab'
tagline:             'Mechatrnocis systems'
description:         'A research group focused on Mechatronics systems of monitoring and effective control'
baseurl:             ''
# baseurl:             ''
source: docs
# About/contact
author:
  name:              Dan Lovell
  url:               http://danlovell.com

# Custom vars
version:             1.1.2
